### ISSUE TITLE
Windows 10 Traceback Error FileNotFound Error

### ISSUE THREAD

**Issue by KAZI131** [sensity-ai/dot#104]
Windows 10 
intel core i7 8th gen 
Installed all assets but cannot run the deepfake. 

`INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter__init.py", line 1892, in call
  File "customtkinter\windows\widgets\ctk_button.py", line 554, in _clicked
    self._command()
  File "ui.py", line 702, in start_button_event
  File "dot__main.py", line 58, in run
  File "dot\dot.py", line 94, in build_option
  File "dot\dot.py", line 219, in fomm
  File "dot\fomm\option.py", line 48, in init
  File "dot\commons\model_option.py", line 49, in init
  File "dot\gpen\face_enhancement.py", line 28, in init
  File "dot\gpen\retinaface\retinaface_detection.py", line 32, in init
  File "dot\gpen\retinaface\retinaface_detection.py", line 60, in load_model
  File "torch\serialization.py", line 594, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "torch\serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "torch\serialization.py", line 211, in init
    super(_open_file, self).init(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: './saved_models/gpen\weights\RetinaFace-R50.pth'`

**Comment by Ghassen-Chaabouni** [comment]
Are you using the executable? This is the new version [link](https://drive.google.com/file/d/1HKj6kYXv8NczLcDI7xDXU7aWXpDGz6vg/view?usp=sharing).  You can try it and confirm if you are still getting the same error or not.
