### ISSUE TITLE
Low FPS with 3070M

### ISSUE THREAD

**Issue by Ganesh2556** [sensity-ai/dot#134]
I am having trouble getting the DOT to run on my laptop. 

 When I run SIMSWAP, it gives an FPS of 4.7. This is much lower than in tests on an AMD Ryzen 5 2600 Six-Core Processor with one NVIDIA GeForce RTX 2070. In the WIN10 resource monitor, the DOT is only using 30% of the GPU memory.

 My laptop configuration is RYZEN 9, RTX 3070M, WIN10.

 Could it be that I'm doing something wrong?

**Comment by Ghassen-Chaabouni** [comment]
Are you using GPEN with SimSwap? If so, what GPEN are you using 256 or 512
Also, are you using SimSwap or SimSwapHQ?
To get the fastest results, use only SimSwap with the option `use_gpu`

**Comment by Ganesh2556** [comment]
> Are you using GPEN with SimSwap? If so, what GPEN are you using 256 or 512 Also, are you using SimSwap or SimSwapHQ? To get the fastest results, use only SimSwap with the option `use_gpu`

I use only SimSwap with the option use_gpu

**Comment by Ghassen-Chaabouni** [comment]
@Ganesh2556 Are you using the default images in the data folder or a custom ones? The speed was measured on these images

**Comment by Ganesh2556** [comment]
> @Ganesh2556 Are you using the default images in the data folder or a custom ones? The speed was measured on these images

I tried to do this with both default and custom images.  I tried to compress the image resolution.  Nothing helped.

**Comment by Ghassen-Chaabouni** [comment]
You mentioned that dot is using 30% of the GPU memory. This means that it's correctly using the GPU. We intentionally made it use low memory so that more users are able to use it. On RTX 3060, I'm getting more than 10fps with SimSwap. 
Are you using DOT alone without any other softwares/emulators? They can lower the fps.

**Comment by OnlyStopOnTop** [comment]
Same for me, using rtx 3070 mobile and have about 4-6 fps.

Only DOT and browser is running on the system - nothing else

**Comment by Ghassen-Chaabouni** [comment]
@OnlyStopOnTop you can confirm if the GPU is being used by running nvidia-smi.
If no memory is allocated to dot then you are using CPU

**Comment by Ganesh2556** [comment]
Matplotlib is building the font cache; this may take a moment.
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
torchvision\models\_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
torchvision\models\_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=None`.
  warnings.warn(msg)
Traceback (most recent call last):
  File "torch\serialization.py", line 354, in _check_seekable
    f.seek(f.tell())
AttributeError: 'NoneType' object has no attribute 'seek'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "dot\__main__.py", line 69, in run
  File "dot\dot.py", line 131, in generate
  File "dot\commons\model_option.py", line 184, in generate_from_camera
  File "dot\simswap\option.py", line 88, in create_model
  File "torch\serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "torch\serialization.py", line 276, in _open_file_like
    return _open_buffer_reader(name_or_buffer)
  File "torch\serialization.py", line 261, in __init__
    _check_seekable(buffer)
  File "torch\serialization.py", line 357, in _check_seekable
    raise_err_msg(["seek", "tell"], e)
  File "torch\serialization.py", line 350, in raise_err_msg
    raise type(e)(msg)
AttributeError: 'NoneType' object has no attribute 'seek'. You can only torch.load from a file that is seekable. Please pre-load the data into a buffer like io.BytesIO and try to load from it instead.

[ WARN:0@132.247] global D:\a\opencv-python\opencv-python\opencv\modules\videoio\src\cap_msmf.cpp (539) `anonymous-namespace'::SourceReaderCB::~SourceReaderCB terminating async callback
