### ISSUE TITLE
Issue with Colab Demo

### ISSUE THREAD

**Issue by CrowVS** [sensity-ai/dot#42]
Hello,

When running the colab demo I encounter this issue when attempting to run the final cell (the one that performs the swap on video):
```
python: can't open file 'scripts/video_swap.py': [Errno 2] No such file or directory
```
If I correct the path to /content/dot/scripts/video_swap.py I get this error:
```
Loading config: ./dot/simswap/configs/config.yaml
Traceback (most recent call last):
  File "scripts/video_swap.py", line 77, in <module>
    main()
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1126, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1051, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1393, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 752, in invoke
    return __callback(*args, **kwargs)
  File "scripts/video_swap.py", line 53, in main
    with open(config) as f:
FileNotFoundError: [Errno 2] No such file or directory: './dot/simswap/configs/config.yaml'
```
Finally, if I move the "dot" folder in "src" to the to the main "dot" folder (following the error above) I receive this error:
```
Traceback (most recent call last):
  File "/content/dot/scripts/video_swap.py", line 10, in <module>
    import dot
ModuleNotFoundError: No module named 'dot'
```

After that I am stumped, though I am sure there is something quite obvious that I am missing.

**Comment by Ghassen-Chaabouni** [comment]
@CrowVS Can you test the colab demo again and check if the issue is fixed?

**Comment by CrowVS** [comment]
@Ghassen-Chaabouni 
I checked and it works, thank you!
