### ISSUE TITLE
windows installation

### ISSUE THREAD

**Issue by kemdolbaeb** [sensity-ai/dot#55]
Can you make an UPDATED step-by-step detailed instructions for windows? At the moment, the steps you have provided do not result in a successful installation of dot on windows.
Please provide exact version of supported CUDA, conda, windows, and what should I type in console to get working pytorch. 
I am constantly getting different errors during various methods of installations.
I even re-installed windows, I've tried many versions of conda, different command lines to get torch etc...
The worst thing is that if you did any of the steps wrong, it becomes clear only at the end. And so you have to try do all the NEW steps (using google) at half-random, including the command lines in terminal. And at the end you will get an new error and you have to do it all over and over again. At this time it's more like a lottery than an installation. Help me, please
It would be great if we had step-by-step tutorial with screenshots and exact versions of each component & command lines to get them.

**Comment by kemdolbaeb** [comment]
File "C:\Users\4\.conda\envs\dot\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\4\.conda\envs\dot\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\4\.conda\envs\dot\Scripts\dot.exe\__main__.py", line 7, in <module>
  File "C:\Users\4\.conda\envs\dot\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\4\.conda\envs\dot\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\4\.conda\envs\dot\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\4\.conda\envs\dot\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)

**Comment by Ghassen-Chaabouni** [comment]
All of the instructions are in the [README](https://github.com/sensity-ai/dot/blob/main/README.md), please don't skip any of the steps.

> Please provide exact version of supported CUDA, conda, windows, and what should I type in console to get working pytorch.

* `dot` was tested on `CUDA 11.1` and Windows 10.
* Download conda from https://www.anaconda.com/
* Install torch `pip install torch==1.9.0+cu111 torchvision==0.10.0+cu111 -f https://download.pytorch.org/whl/torch_stable.html`

> File "C:\Users\4.conda\envs\dot\lib\runpy.py", line 194, in _run_module_as_main
return _run_code(code, main_globals, None,
File "C:\Users\4.conda\envs\dot\lib\runpy.py", line 87, in run_code
exec(code, run_globals)
File "C:\Users\4.conda\envs\dot\Scripts\dot.exe_main.py", line 7, in
File "C:\Users\4.conda\envs\dot\lib\site-packages\click\core.py", line 1130, in call
return self.main(*args, **kwargs)
File "C:\Users\4.conda\envs\dot\lib\site-packages\click\core.py", line 1055, in main
rv = self.invoke(ctx)
File "C:\Users\4.conda\envs\dot\lib\site-packages\click\core.py", line 1404, in invoke
return ctx.invoke(self.callback, **ctx.params)
File "C:\Users\4.conda\envs\dot\lib\site-packages\click\core.py", line 760, in invoke
return __callback(*args, **kwargs)
whats the problem? I did everything according with the manual

Did you follow all of the instructions? What command did you run? And can you run `dot --help` without any errors?

**Comment by kemdolbaeb** [comment]
I followed all the instructions carefully and consistently. 
You tell me to download https://www.anaconda.com/. It running python 3.9 while dot requires for 3.8 as indicated in the manual. 
In spite of this, I continued the installation following your answer

I open anaconda prompt  exe, installed cuda_11.1.0_456.43_win10.exe

C:\Users\4> cd C:\Users\4\dot-1.1.0
conda env create -f envs/environment-gpu.yaml
pip install torch==1.9.0+cu111 torchvision==0.10.0+cu111 -f https://download.pytorch.org/whl/torch_stable.html
conda activate dot
pip install -e .
and got this error.
Package 'dot' requires a different Python: 3.9.13 not in '<3.9,>=3.8'
closed terminal
then
conda install python=3.8
conda activate dot
pip install -e .

  File "C:\Users\4\anaconda3\envs\dot\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\4\anaconda3\envs\dot\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\4\anaconda3\envs\dot\Scripts\dot.exe\__main__.py", line 7, in <module>
  File "C:\Users\4\anaconda3\envs\dot\lib\site-packages\click\core.py", line 1126, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\4\anaconda3\envs\dot\lib\site-packages\click\core.py", line 1051, in main
    rv = self.invoke(ctx)
  File "C:\Users\4\anaconda3\envs\dot\lib\site-packages\click\core.py", line 1393, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\4\anaconda3\envs\dot\lib\site-packages\click\core.py", line 752, in invoke
    return __callback(*args, **kwargs)

**Comment by kemdolbaeb** [comment]
dot -c ./configs/simswap.yaml --target data/ --source "data/" --save_folder test_local/ --use_image --use_gpu

results this 
Traceback (most recent call last):
  File "C:\Users\4\anaconda3\envs\dot\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\4\anaconda3\envs\dot\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\4\anaconda3\envs\dot\Scripts\dot.exe\__main__.py", line 7, in <module>
  File "C:\Users\4\anaconda3\envs\dot\lib\site-packages\click\core.py", line 1126, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\4\anaconda3\envs\dot\lib\site-packages\click\core.py", line 1051, in main
    rv = self.invoke(ctx)
  File "C:\Users\4\anaconda3\envs\dot\lib\site-packages\click\core.py", line 1393, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\4\anaconda3\envs\dot\lib\site-packages\click\core.py", line 752, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\4\dot-1.1.0\src\dot\__main__.py", line 204, in main
    run(
  File "C:\Users\4\dot-1.1.0\src\dot\__main__.py", line 66, in run
    _dot.generate(
  File "C:\Users\4\dot-1.1.0\src\dot\dot.py", line 142, in generate
    [swappedDict, rejectedDict] = option.generate_from_image(
  File "C:\Users\4\dot-1.1.0\src\dot\commons\model_option.py", line 104, in generate_from_image
    self.create_model(**kwargs)
  File "C:\Users\4\dot-1.1.0\src\dot\simswap\option.py", line 80, in create_model
    self.spNorm = SpecificNorm(use_gpu=self.use_gpu)
  File "C:\Users\4\dot-1.1.0\src\dot\simswap\util\norm.py", line 17, in __init__
    self.mean = torch.from_numpy(self.mean).float().cuda()
  File "C:\Users\4\anaconda3\envs\dot\lib\site-packages\torch\cuda\__init__.py", line 166, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled

**Comment by kemdolbaeb** [comment]
Thank you so much for replying! I re-installed windows, cmake, visual studio, installed miniconda instead of anaconda, solved dlib and cmake error, installed cudatoolkit and now I'm getting this

(dot) C:\Users\4\dot-main>python -c "import torch; print(torch.cuda.is_available())"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\4\miniconda3\envs\dot\lib\site-packages\torch\__init__.py", line 128, in <module>
    raise err
OSError: [WinError 127] The specified procedure could not be found. Error loading "C:\Users\4\miniconda3\envs\dot\lib\site-packages\torch\lib\caffe2_detectron_ops.dll" or one of its dependencies.

What is the problem? 

I don't have the energy for today to continue this torment. I'll be back tomorrow, feeling like I need to delete miniconda and install anaconda. Please don't close the thread, I'll have more questions. Thanks in advance!

I also think maybe I execute some commands not from the correct directory. Should I install cudatoolkit , torch and torchvision  after `conda activate dot`  in (dot) C:\Users\4\dot-main  ? Or it should be installed in/from  (base) C:\Users\4\dot-main> ?

**Comment by Ghassen-Chaabouni** [comment]
>  also think maybe I execute some commands not from the correct directory. Should I install cudatoolkit , torch and torchvision after conda activate dot in (dot) C:\Users\4\dot-main ? Or it should be installed in/from (base) C:\Users\4\dot-main> ?

Yes install them after `conda activate dot`. The instructions that I sent in my earlier response are in order
```
conda env create -f envs/environment-gpu.yaml
conda activate dot
conda install cudatoolkit=11.1
pip install torch==1.9.0+cu111 torchvision==0.10.0+cu111 -f https://download.pytorch.org/whl/torch_stable.html
pip install -e .
```

About this error

> Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\4\miniconda3\envs\dot\lib\site-packages\torch\__init__.py", line 128, in <module>
    raise err
OSError: [WinError 127] The specified procedure could not be found. Error loading "C:\Users\4\miniconda3\envs\dot\lib\site-packages\torch\lib\caffe2_detectron_ops.dll" or one of its dependencies.

Try the top answer from here it may solve it https://stackoverflow.com/questions/63629075/error-in-training-opennmt-caffe2-detectron-ops-dll-not-found

> https://github.com/pytorch/pytorch/issues/35803#issuecomment-725285085
This answer worked for me.
Just deleting "caffe2_detectron_ops.dll" from the path ("C:\Users\Girish\AppData\Local\Programs\Python\Python38\lib\sitepackages\torch\lib\caffe2_detectron_ops.dll")

**Comment by kemdolbaeb** [comment]
I keep going. Got this error while installing ```pip install torch==1.9.0+cu111 torchvision==0.10.0+cu111 -f https://download.pytorch.org/whl/torch_stable.html
pip install -e .```

```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
torchaudio 0.13.1 requires torch==1.13.1, but you have torch 1.9.0+cu111 which is incompatible.
Successfully installed torch-1.9.0+cu111 torchvision-0.10.0+cu111
```

latest anaconda, python 3.8 downgraded

**Comment by giorgiop** [comment]
Feel free to open other issue for other topics!

**Comment by PiPappaPeroPo** [comment]
Hi guys, I installed dot "successfully" but when i type `dot --help` this error occurs 

```
from .layers.functions.prior_box import PriorBox
ModuleNotFoundError: No module named 'dot.gpen.retinaface.layers.functions'
```

i installed cuda toolkit, torch and torchvision with no error but if i type
 `python -c "import torch; print(torch.cuda.is_available())" ` it says _False_

What can I do? Thanks in advance

**Comment by llama369** [comment]
> Thank you so much for replying! I re-installed windows, cmake, visual studio, installed miniconda instead of anaconda, solved dlib and cmake error, installed cudatoolkit with `conda install pytorch torchvision torchaudio cudatoolkit=11.1 -c pytorch -c conda-forge` and now I'm getting this
> 
> ```
> (dot) C:\Users\4\dot-main>`python -c "import torch; print(torch.cuda.is_available())"`
> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
>   File "C:\Users\4\miniconda3\envs\dot\lib\site-packages\torch\__init__.py", line 128, in <module>
>     raise err
> OSError: [WinError 127] The specified procedure could not be found. Error loading "C:\Users\4\miniconda3\envs\dot\lib\site-packages\torch\lib\caffe2_detectron_ops.dll" or one of its dependencies.
> ```
> 
> ```
> (dot) C:\Users\4\dot-main>dot --help
> Traceback (most recent call last):
>   File "C:\Users\4\miniconda3\envs\dot\lib\runpy.py", line 194, in _run_module_as_main
>     return _run_code(code, main_globals, None,
>   File "C:\Users\4\miniconda3\envs\dot\lib\runpy.py", line 87, in _run_code
>     exec(code, run_globals)
>   File "C:\Users\4\miniconda3\envs\dot\Scripts\dot.exe\__main__.py", line 4, in <module>
>   File "C:\Users\4\dot-main\src\dot\__init__.py", line 7, in <module>
>     from .dot import DOT
>   File "C:\Users\4\dot-main\src\dot\dot.py", line 10, in <module>
>     from .commons import ModelOption
>   File "C:\Users\4\dot-main\src\dot\commons\__init__.py", line 7, in <module>
>     from .model_option import ModelOption
>   File "C:\Users\4\dot-main\src\dot\commons\model_option.py", line 12, in <module>
>     import torch
>   File "C:\Users\4\miniconda3\envs\dot\lib\site-packages\torch\__init__.py", line 128, in <module>
>     raise err
> OSError: [WinError 127] The specified procedure could not be found. Error loading "C:\Users\4\miniconda3\envs\dot\lib\site-packages\torch\lib\caffe2_detectron_ops.dll" or one of its dependencies.
> ```
> 
> What is the problem?
> 
> I don't have the energy for today to continue this torment. I'll be back tomorrow, feeling like I need to delete miniconda and install anaconda. Please don't close the thread, I'll have more questions. Thanks in advance!
> 
> I also think maybe I execute some commands not from the correct directory. Should I install cudatoolkit , torch and torchvision after `conda activate dot` in (dot) C:\Users\4\dot-main ? Or it should be installed in/from (base) C:\Users\4\dot-main> ?

Hello, I'm facing the same problems, when I try to install on Windows 10 I get :

```
...
Collecting colorama
  Using cached colorama-0.4.6-py2.py3-none-any.whl (25 kB)
Requirement already satisfied: setuptools in c:\users\toto\miniconda3\envs\dot\lib\site-packages (from numba==0.55.2->-r C:\Users\toto\Downloads\dot-1.1.0\dot-1.1.0\envs\../requirements.txt (line 43)) (67.7.2)
Building wheels for collected packages: dlib
  Building wheel for dlib (setup.py): started
  Building wheel for dlib (setup.py): finished with status 'error'
  Running setup.py clean for dlib
Failed to build dlib
Installing collected packages: six, pyparsing, pillow, numpy, typing-extensions, tifffile, scipy, pywavelets, python-dateutil, packaging, networkx, llvmlite, kiwisolver, imageio, fonttools, cycler, colorama, wheel, urllib3, tqdm, torch, scikit-image, protobuf, opencv-python, opencv-contrib-python, numba, matplotlib, idna, flatbuffers, chardet, certifi, attrs, absl-py, torchvision, requests, pyyaml, onnxruntime-gpu, onnxruntime, mediapipe, kornia, face-alignment, dlib, click
  Attempting uninstall: wheel
    Found existing installation: wheel 0.40.0
    Uninstalling wheel-0.40.0:
      Successfully uninstalled wheel-0.40.0

Pip subprocess error:
  ERROR: Command errored out with exit status 1:
   command: 'C:\Users\toto\miniconda3\envs\dot\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\toto\\AppData\\Local\\Temp\\pip-install-d91gsh9k\\dlib_b30d6b766bdc47bab99c93858f791031\\setup.py'"'"'; __file__='"'"'C:\\Users\\toto\\AppData\\Local\\Temp\\pip-install-d91gsh9k\\dlib_b30d6b766bdc47bab99c93858f791031\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\toto\AppData\Local\Temp\pip-wheel-r3cxqrdv'
       cwd: C:\Users\toto\AppData\Local\Temp\pip-install-d91gsh9k\dlib_b30d6b766bdc47bab99c93858f791031\
  Complete output (64 lines):
  running bdist_wheel
  running build
  running build_py
  running build_ext
  C:\Users\toto\AppData\Local\Temp\pip-install-d91gsh9k\dlib_b30d6b766bdc47bab99c93858f791031\setup.py:131: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
    if LooseVersion(cmake_version) < '3.1.0':
  Building extension for Python 3.8.17 | packaged by conda-forge | (default, Jun 16 2023, 07:01:59) [MSC v.1929 64 bit (AMD64)]
  Invoking CMake setup: 'cmake C:\Users\toto\AppData\Local\Temp\pip-install-d91gsh9k\dlib_b30d6b766bdc47bab99c93858f791031\tools\python -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\Users\toto\AppData\Local\Temp\pip-install-d91gsh9k\dlib_b30d6b766bdc47bab99c93858f791031\build\lib.win-amd64-cpython-38 -DPYTHON_EXECUTABLE=C:\Users\toto\miniconda3\envs\dot\python.exe -DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=C:\Users\toto\AppData\Local\Temp\pip-install-d91gsh9k\dlib_b30d6b766bdc47bab99c93858f791031\build\lib.win-amd64-cpython-38 -A x64'
  -- Building for: NMake Makefiles
  CMake Error at CMakeLists.txt:3 (project):
    Generator

      NMake Makefiles

    does not support platform specification, but platform

      x64

    was specified.


  CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
  CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
  -- Configuring incomplete, errors occurred!
  See also "C:/Users/toto/AppData/Local/Temp/pip-install-d91gsh9k/dlib_b30d6b766bdc47bab99c93858f791031/build/temp.win-amd64-cpython-38/Release/CMakeFiles/CMakeOutput.log".
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\toto\AppData\Local\Temp\pip-install-d91gsh9k\dlib_b30d6b766bdc47bab99c93858f791031\setup.py", line 223, in <module>
      setup(
    File "C:\Users\toto\miniconda3\envs\dot\lib\site-packages\setuptools\__init__.py", line 107, in setup
      return distutils.core.setup(**attrs)
    File "C:\Users\toto\miniconda3\envs\dot\lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
      return run_commands(dist)
    File "C:\Users\toto\miniconda3\envs\dot\lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
      dist.run_commands()
    File "C:\Users\toto\miniconda3\envs\dot\lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
      self.run_command(cmd)
    File "C:\Users\toto\miniconda3\envs\dot\lib\site-packages\setuptools\dist.py", line 1244, in run_command
      super().run_command(command)
    File "C:\Users\toto\miniconda3\envs\dot\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
      cmd_obj.run()
    File "C:\Users\toto\miniconda3\envs\dot\lib\site-packages\wheel\bdist_wheel.py", line 343, in run
      self.run_command("build")
    File "C:\Users\toto\miniconda3\envs\dot\lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
      self.distribution.run_command(command)
    File "C:\Users\toto\miniconda3\envs\dot\lib\site-packages\setuptools\dist.py", line 1244, in run_command
      super().run_command(command)
    File "C:\Users\toto\miniconda3\envs\dot\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
      cmd_obj.run()
    File "C:\Users\toto\miniconda3\envs\dot\lib\site-packages\setuptools\_distutils\command\build.py", line 131, in run
      self.run_command(cmd_name)
    File "C:\Users\toto\miniconda3\envs\dot\lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
      self.distribution.run_command(command)
    File "C:\Users\toto\miniconda3\envs\dot\lib\site-packages\setuptools\dist.py", line 1244, in run_command
      super().run_command(command)
    File "C:\Users\toto\miniconda3\envs\dot\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
      cmd_obj.run()
    File "C:\Users\toto\AppData\Local\Temp\pip-install-d91gsh9k\dlib_b30d6b766bdc47bab99c93858f791031\setup.py", line 135, in run
      self.build_extension(ext)
    File "C:\Users\toto\AppData\Local\Temp\pip-install-d91gsh9k\dlib_b30d6b766bdc47bab99c93858f791031\setup.py", line 172, in build_extension
      subprocess.check_call(cmake_setup, cwd=build_folder)
    File "C:\Users\toto\miniconda3\envs\dot\lib\subprocess.py", line 364, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['cmake', 'C:\\Users\\toto\\AppData\\Local\\Temp\\pip-install-d91gsh9k\\dlib_b30d6b766bdc47bab99c93858f791031\\tools\\python', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\\Users\\toto\\AppData\\Local\\Temp\\pip-install-d91gsh9k\\dlib_b30d6b766bdc47bab99c93858f791031\\build\\lib.win-amd64-cpython-38', '-DPYTHON_EXECUTABLE=C:\\Users\\toto\\miniconda3\\envs\\dot\\python.exe', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=C:\\Users\\toto\\AppData\\Local\\Temp\\pip-install-d91gsh9k\\dlib_b30d6b766bdc47bab99c93858f791031\\build\\lib.win-amd64-cpython-38', '-A', 'x64']' returned non-zero exit status 1.
  ----------------------------------------
  ERROR: Failed building wheel for dlib
ERROR: Could not install packages due to an OSError: [WinError 5] Access is denied: 'C:\\Users\\toto\\AppData\\Local\\Temp\\pip-uninstall-tlc6c6m4\\wheel.exe'
Consider using the `--user` option or check the permissions.


failed

CondaEnvException: Pip failed
```

What are the steps to solve CMAKE and dlib errors ?
Thanks
