### ISSUE TITLE
run dot 

### ISSUE THREAD

**Issue by bebetik** [sensity-ai/dot#73]
When I try to start the point, it gives an error, what do I have to do?

(dot) C:\Users\1\dot-main>dot -c ./configs/simswap.yaml --target 0 --source "./data" --use_gpu
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
Traceback (most recent call last):
  File "C:\Users\1\miniconda3\envs\dot\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\1\miniconda3\envs\dot\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\1\miniconda3\envs\dot\Scripts\dot.exe\__main__.py", line 7, in <module>
  File "C:\Users\1\miniconda3\envs\dot\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\1\miniconda3\envs\dot\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\1\miniconda3\envs\dot\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\1\miniconda3\envs\dot\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\1\dot-main\src\dot\__main__.py", line 206, in main
    run(
  File "C:\Users\1\dot-main\src\dot\__main__.py", line 67, in run
    _dot.generate(
  File "C:\Users\1\dot-main\src\dot\dot.py", line 131, in generate
    option.generate_from_camera(
  File "C:\Users\1\dot-main\src\dot\commons\model_option.py", line 184, in generate_from_camera
    self.create_model(opt_crop_size=opt_crop_size, **kwargs)
  File "C:\Users\1\dot-main\src\dot\simswap\option.py", line 80, in create_model
    self.spNorm = SpecificNorm(use_gpu=self.use_gpu)
  File "C:\Users\1\dot-main\src\dot\simswap\util\norm.py", line 17, in __init__
    self.mean = torch.from_numpy(self.mean).float().cuda()
  File "C:\Users\1\miniconda3\envs\dot\lib\site-packages\torch\cuda\__init__.py", line 221, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled

(dot) C:\Users\1\dot-main>dot
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
Usage: dot [OPTIONS]
Try 'dot --help' for help.

Error: Missing option '--source'.

**Comment by Ghassen-Chaabouni** [comment]
Did you run all of the installation instructions mentioned in the [README.md](https://github.com/sensity-ai/dot/blob/main/README.md) ?

```conda env create -f envs/environment-gpu.yaml
conda activate dot
conda install cudatoolkit=11.1
pip install torch==1.9.0+cu111 torchvision==0.10.0+cu111 -f https://download.pytorch.org/whl/torch_stable.html
pip install -e .
```

**Comment by Ghassen-Chaabouni** [comment]
@bebetik Are there any updates about this issue?
