### ISSUE TITLE
Torch and torchvision check issue

### ISSUE THREAD

**Issue by OnlyStopOnTop** [sensity-ai/dot#77]
### Description:

last step was installing torch and toch vision:

conda install pytorch torchvision torchaudio pytorch-cuda=11.7 -c pytorch -c nvidia

after checking with:

python -c "import torch; print(torch.cuda.is_available())

I get error:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\user1\miniconda3\envs\dot\lib\site-packages\torch\__init__.py", line 122, in <module>
    raise err
OSError: [WinError 127] Die angegebene Prozedur wurde nicht gefunden. Error loading "C:\Users\user1\miniconda3\envs\dot\lib\site-packages\torch\lib\caffe2_detectron_ops.dll" or one of its dependencies.

Wrong torch or cudatoolkit version?

I downloaded pytorch cuda 11.7 and cudatoolki 11.3.1 ( conda install -c anaconda cudatoolkit).

Need help

**Comment by OnlyStopOnTop** [comment]
up!

**Comment by OnlyStopOnTop** [comment]
up!

**Comment by Ghassen-Chaabouni** [comment]
@OnlyStopOnTop Check this issue https://github.com/sensity-ai/dot/issues/55. Someone already had a similar issue as you

**Comment by Ghassen-Chaabouni** [comment]
Closing due to inactivity. Feel free to reopen the issue.
