### ISSUE TITLE
SimSwap & SimSwap HQ are not working

### ISSUE THREAD

**Issue by OnlyStopOnTop** [sensity-ai/dot#79]
## :bug: Bug Report
SimSwap and SimswapHQ are not working.
FOMM and faceswapping are.

As I try to run SimSwap I get the error code below:

```
(dot) C:\Users\alber\Desktop\dot-main>dot -c ./configs/simswap.yaml --target 0 --source "./data" --use_gpu
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
C:\Users\alber\miniconda3\envs\dot\lib\site-packages\torch\serialization.py:888: SourceChangeWarning: source code of class 'torch.nn.parallel.data_parallel.DataParallel' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
C:\Users\alber\miniconda3\envs\dot\lib\site-packages\torch\serialization.py:888: SourceChangeWarning: source code of class 'models.ArcMarginModel' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
C:\Users\alber\miniconda3\envs\dot\lib\site-packages\torch\serialization.py:888: SourceChangeWarning: source code of class 'models.ResNet' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
C:\Users\alber\miniconda3\envs\dot\lib\site-packages\torch\serialization.py:888: SourceChangeWarning: source code of class 'torch.nn.modules.conv.Conv2d' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
C:\Users\alber\miniconda3\envs\dot\lib\site-packages\torch\serialization.py:888: SourceChangeWarning: source code of class 'torch.nn.modules.batchnorm.BatchNorm2d' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
C:\Users\alber\miniconda3\envs\dot\lib\site-packages\torch\serialization.py:888: SourceChangeWarning: source code of class 'torch.nn.modules.activation.PReLU' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
C:\Users\alber\miniconda3\envs\dot\lib\site-packages\torch\serialization.py:888: SourceChangeWarning: source code of class 'torch.nn.modules.pooling.MaxPool2d' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
C:\Users\alber\miniconda3\envs\dot\lib\site-packages\torch\serialization.py:888: SourceChangeWarning: source code of class 'torch.nn.modules.container.Sequential' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
C:\Users\alber\miniconda3\envs\dot\lib\site-packages\torch\serialization.py:888: SourceChangeWarning: source code of class 'models.SEBlock' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
C:\Users\alber\miniconda3\envs\dot\lib\site-packages\torch\serialization.py:888: SourceChangeWarning: source code of class 'torch.nn.modules.pooling.AdaptiveAvgPool2d' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
C:\Users\alber\miniconda3\envs\dot\lib\site-packages\torch\serialization.py:888: SourceChangeWarning: source code of class 'torch.nn.modules.linear.Linear' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
C:\Users\alber\miniconda3\envs\dot\lib\site-packages\torch\serialization.py:888: SourceChangeWarning: source code of class 'torch.nn.modules.activation.Sigmoid' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
C:\Users\alber\miniconda3\envs\dot\lib\site-packages\torch\serialization.py:888: SourceChangeWarning: source code of class 'torch.nn.modules.dropout.Dropout' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
C:\Users\alber\miniconda3\envs\dot\lib\site-packages\torch\serialization.py:888: SourceChangeWarning: source code of class 'torch.nn.modules.batchnorm.BatchNorm1d' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
Traceback (most recent call last):
  File "C:\Users\alber\miniconda3\envs\dot\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\alber\miniconda3\envs\dot\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\alber\miniconda3\envs\dot\Scripts\dot.exe\__main__.py", line 7, in <module>
  File "C:\Users\alber\miniconda3\envs\dot\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\alber\miniconda3\envs\dot\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\alber\miniconda3\envs\dot\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\alber\miniconda3\envs\dot\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\alber\Desktop\dot-main\src\dot\__main__.py", line 206, in main
    run(
  File "C:\Users\alber\Desktop\dot-main\src\dot\__main__.py", line 67, in run
    _dot.generate(
  File "C:\Users\alber\Desktop\dot-main\src\dot\dot.py", line 131, in generate
    option.generate_from_camera(
  File "C:\Users\alber\Desktop\dot-main\src\dot\commons\model_option.py", line 184, in generate_from_camera
    self.create_model(opt_crop_size=opt_crop_size, **kwargs)
  File "C:\Users\alber\Desktop\dot-main\src\dot\simswap\option.py", line 100, in create_model
    self.model = create_model(
  File "C:\Users\alber\Desktop\dot-main\src\dot\simswap\models\models.py", line 31, in create_model
    model.initialize(
  File "C:\Users\alber\Desktop\dot-main\src\dot\simswap\fs_model.py", line 76, in initialize
    netArc_checkpoint = torch.load(arcface_model_path)
  File "C:\Users\alber\miniconda3\envs\dot\lib\site-packages\torch\serialization.py", line 815, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "C:\Users\alber\miniconda3\envs\dot\lib\site-packages\torch\serialization.py", line 1043, in _legacy_load
    result = unpickler.load()
  File "C:\Users\alber\miniconda3\envs\dot\lib\site-packages\torch\optim\sgd.py", line 30, in __setstate__
    super().__setstate__(state)
  File "C:\Users\alber\miniconda3\envs\dot\lib\site-packages\torch\optim\optimizer.py", line 214, in __setstate__
    self.defaults.setdefault('differentiable', False)
AttributeError: 'SGD' object has no attribute 'defaults'
[ WARN:0@5.669] global D:\a\opencv-python\opencv-python\opencv\modules\videoio\src\cap_msmf.cpp (539) `anonymous-namespace'::SourceReaderCB::~SourceReaderCB terminating async callback
```

Best regards

**Comment by OnlyStopOnTop** [comment]
I run torch 2.0 with CUDA 11.8 
I checked the list for compatibility and that´s why I choosed torch 2.0

I´m not sure if torch 1.9 is for cuda 11.8

**Comment by Ghassen-Chaabouni** [comment]
> I run torch 2.0 with CUDA 11.8 I checked the list for compatibility and that´s why I choosed torch 2.0
> 
> I´m not sure if torch 1.9 is for cuda 11.8

How about you try first installing torch 1.9 with cuda 11.1 and see if it will work
`pip install torch==1.9.0+cu111 torchvision==0.10.0+cu111 -f https://download.pytorch.org/whl/torch_stable.html`

If it doesn't work, as a second step try downgrading cuda to version 11.1

**Comment by OnlyStopOnTop** [comment]
Unisntalled torch and cuda completly.

Installed CUDA 11.1

entering:

pip install torch==1.9.0+cu111 torchvision==0.10.0+cu111 -f https://download.pytorch.org/whl/torch_stable.html

Conda Error:

Traceback (most recent call last):
  File "C:\Users\alber\miniconda3\envs\dot\lib\site-packages\pip\_vendor\urllib3\response.py", line 438, in _error_catcher
    yield
  File "C:\Users\alber\miniconda3\envs\dot\lib\site-packages\pip\_vendor\urllib3\response.py", line 519, in read
    data = self._fp.read(amt) if not fp_closed else b""
  File "C:\Users\alber\miniconda3\envs\dot\lib\site-packages\pip\_vendor\cachecontrol\filewrapper.py", line 62, in read
    data = self.__fp.read(amt)
  File "C:\Users\alber\miniconda3\envs\dot\lib\http\client.py", line 459, in read
    n = self.readinto(b)
  File "C:\Users\alber\miniconda3\envs\dot\lib\http\client.py", line 503, in readinto
    n = self.fp.readinto(b)
  File "C:\Users\alber\miniconda3\envs\dot\lib\socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "C:\Users\alber\miniconda3\envs\dot\lib\ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Users\alber\miniconda3\envs\dot\lib\ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\alber\miniconda3\envs\dot\lib\site-packages\pip\_internal\cli\base_command.py", line 164, in exc_logging_wrapper
    status = run_func(*args)
  File "C:\Users\alber\miniconda3\envs\dot\lib\site-packages\pip\_internal\cli\req_command.py", line 205, in wrapper
    return func(self, options, args)
  File "C:\Users\alber\miniconda3\envs\dot\lib\site-packages\pip\_internal\commands\install.py", line 338, in run
    requirement_set = resolver.resolve(
  File "C:\Users\alber\miniconda3\envs\dot\lib\site-packages\pip\_internal\resolution\resolvelib\resolver.py", line 92, in resolve
    result = self._result = resolver.resolve(
  File "C:\Users\alber\miniconda3\envs\dot\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 482, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "C:\Users\alber\miniconda3\envs\dot\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 349, in resolve
    self._add_to_criteria(self.state.criteria, r, parent=None)
  File "C:\Users\alber\miniconda3\envs\dot\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 173, in _add_to_criteria
    if not criterion.candidates:
  File "C:\Users\alber\miniconda3\envs\dot\lib\site-packages\pip\_vendor\resolvelib\structs.py", line 151, in __bool__
    return bool(self._sequence)
  File "C:\Users\alber\miniconda3\envs\dot\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 155, in __bool__
    return any(self)
  File "C:\Users\alber\miniconda3\envs\dot\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 143, in <genexpr>
    return (c for c in iterator if id(c) not in self._incompatible_ids)
  File "C:\Users\alber\miniconda3\envs\dot\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 47, in _iter_built
    candidate = func()
  File "C:\Users\alber\miniconda3\envs\dot\lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 201, in _make_candidate_from_link
    self._link_candidate_cache[link] = LinkCandidate(
  File "C:\Users\alber\miniconda3\envs\dot\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 281, in __init__
    super().__init__(
  File "C:\Users\alber\miniconda3\envs\dot\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 156, in __init__
    self.dist = self._prepare()
  File "C:\Users\alber\miniconda3\envs\dot\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 225, in _prepare
    dist = self._prepare_distribution()
  File "C:\Users\alber\miniconda3\envs\dot\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 292, in _prepare_distribution
    return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
  File "C:\Users\alber\miniconda3\envs\dot\lib\site-packages\pip\_internal\operations\prepare.py", line 482, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
  File "C:\Users\alber\miniconda3\envs\dot\lib\site-packages\pip\_internal\operations\prepare.py", line 527, in _prepare_linked_requirement
    local_file = unpack_url(
  File "C:\Users\alber\miniconda3\envs\dot\lib\site-packages\pip\_internal\operations\prepare.py", line 213, in unpack_url
    file = get_http_url(
  File "C:\Users\alber\miniconda3\envs\dot\lib\site-packages\pip\_internal\operations\prepare.py", line 94, in get_http_url
    from_path, content_type = download(link, temp_dir.path)
  File "C:\Users\alber\miniconda3\envs\dot\lib\site-packages\pip\_internal\network\download.py", line 145, in __call__
    for chunk in chunks:
  File "C:\Users\alber\miniconda3\envs\dot\lib\site-packages\pip\_internal\cli\progress_bars.py", line 144, in iter
    for x in it:
  File "C:\Users\alber\miniconda3\envs\dot\lib\site-packages\pip\_internal\network\utils.py", line 63, in response_chunks
    for chunk in response.raw.stream(
  File "C:\Users\alber\miniconda3\envs\dot\lib\site-packages\pip\_vendor\urllib3\response.py", line 576, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "C:\Users\alber\miniconda3\envs\dot\lib\site-packages\pip\_vendor\urllib3\response.py", line 541, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "C:\Users\alber\miniconda3\envs\dot\lib\contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\Users\alber\miniconda3\envs\dot\lib\site-packages\pip\_vendor\urllib3\response.py", line 443, in _error_catcher
    raise ReadTimeoutError(self._pool, None, "Read timed out.")
pip._vendor.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='download.pytorch.org', port=443): Read timed out.

**Comment by giorgiop** [comment]
@OnlyStopOnTop we now provide windows exes , can you give a try?

**Comment by Ghassen-Chaabouni** [comment]
This issue is outdated. Feel free to reopen the issue after pulling the latest updates
